### PR TITLE
Replace record.msg with getMessage() as it has all the variables parsed

### PR DESCRIPTION
**Pull request by halkeye**
I think this is a fix for just more recent versions of gunicorn, but i can't easily setup older versions to test.

### CODE REVIEW

**Comment by halkeye** [comment]
looks like @williln might be someone worth pinging, but isn't watching the repo 👋

**Comment by frankwiles** [comment]
@halkeye thanks sorry this slipped through the cracks on us.  Having @gladiatr72 review it and we'll merge it then.

**Comment by halkeye** [comment]
Exciting.

I'm no longer employed doing python so can't really test it anymore so I hope it still works.

**Comment by benregn** [comment]
I can confirm that `master` does not work on `gunicorn==19.9.0` but this patch does 👍

**Comment by frankwiles** [comment]
@gladiatr72 want to give it a whirl and merge it?

**Comment by EricTendian** [comment]
Just bumping this as I'm running into the same issue, I can also confirm what @benregn said.

@frankwiles @gladiatr72 @fcurella any one of you able to review this and merge? Thanks!

**Comment by gladiatr72** [comment]
doh!  Yes.  Will look at this today :)

**Comment by frankwiles** [comment]
@gladiatr72 this good to go?

**Comment by gladiatr72** [comment]
@halkeye thank you from the future :grin:

**Comment by halkeye** [comment]
Yay from the present

**Pull request merged**
